### ISSUE TITLE
[Suggestion] Adding a Date key

### ISSUE THREAD

**Issue by ghost** [joakimoa/copywithcontext#1]
Hi,

Just discovered, installed and now running flawlessly _Copy With Context_ (CWC) 2.0

A simple suggestion, that of adding a DATE key, i.e. `{CWC_DATE}`

I most appreciate the availability of ordering and formatting of the text.
I personally opt for:
```
{CWC_TITLE}
{CWC_URL}
---
{CWC_TEXT}
```
which allows, i.e. CWC's introduction on AMO:

```
Copy With Context – Get this Extension for 🦊 Firefox (en-US)
https://addons.mozilla.org/en-US/firefox/addon/copy-with-context/
---
The order and formatting of the text can be modified through the extension preferences.
```
With a DATE key we could have, with the same example,
```
Copy With Context – Get this Extension for 🦊 Firefox (en-US)
https://addons.mozilla.org/en-US/firefox/addon/copy-with-context/
Wed Aug 12 2020 11:15:37 GMT+0200
---
The order and formatting of the text can be modified through the extension preferences.
```
and that would be the cherry on the cake!

My argument: I guess I'm not the only one to refer to a page reference saved with a tool such as CWC and to appreciate having the date/time it was copy/pasted included.

Only a suggestion: Runs nicely as is.
Thanks.

**Comment by joakimoa** [comment]
Glad you like the extension!

That's a really good suggestion and something I can see myself using as well. I'll look into adding a date key.
